### ISSUE TITLE
savePayment가 함수가 아니라고 나옵니다

### ISSUE THREAD

**Issue by codesejin** [plus-tdd/animalNest#52]
api를 인터페이스 적용하고나서 한번도 테스트 못하다가 오늘 테스트해봤는뎁,, 작동을 안해서 질문드리려고합니답,,

```
listening on port 3000
[2023-07-26 17:17:41] [info] [application.main] : Hello, World!!!!! 로그 성공
[Nest] 45026  - 07/26/2023, 5:19:08 PM   ERROR [ExceptionsHandler] this.repository.savePayment is not a function
TypeError: this.repository.savePayment is not a function
    at PaymentService.makePayment (/Users/sejinpark/node/animalNest/dist/main.js:2310:49)
    at PaymentController.makePayment (/Users/sejinpark/node/animalNest/dist/main.js:2243:36)
    at /Users/sejinpark/node/animalNest/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/sejinpark/node/animalNest/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /Users/sejinpark/node/animalNest/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

현재 서비스에서 repository의 인터페이스를 불러오고, 
payment.db.ts에서는 인터페이스를 구현한 savePayment를 사용하려고 하는데, 왜 해당 에러가 뜨는건지 잘 모르겠습니답..  
아래코드는 payment.module.ts -> payment.service.ts -> payment.repository.ts -> payment.db.ts 순서대로입니답

```
//payment.module.ts
import { Module } from '@nestjs/common';
import { PaymentController } from './api/payment.controller';
import { TestPaymentRepository } from './domain/payment.repository'; // PaymentRepository import 추가
//import { JwtStrategy } from '../auth/passport/auth.passport';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PaymentEntity } from './data/payment.entity';
import { PaymentService } from './domain/payment.service';
import { PaymentRepositoryImpl } from './data/payment.db';
import { AlarmService, AlarmServiceImpl } from '../alarm/alarm.service';
import { AlarmModule } from '../alarm/alarm.module';
import { AuthModule } from '../auth/auth.module';
import { UserEntity } from '../user/data/user.entity';

@Module({
  imports: [
    AuthModule,
    TypeOrmModule.forFeature([PaymentEntity, UserEntity]),
    AlarmModule
  ],
  controllers: [PaymentController],
  providers: [
    PaymentService,
    {
      provide: 'PaymentRepository',
      useClass: PaymentRepositoryImpl,
    },
    {
      provide: 'AlarmService',
      useClass: AlarmServiceImpl,
    },
  ],
  exports: [
    {
      provide: 'PaymentRepository',
      useClass: PaymentRepositoryImpl,
    },
    {
      provide: 'AlarmService',
      useClass: AlarmServiceImpl,
    },
  ],
})
export class PaymentModule {}

```

```
// payment.service.ts

import { Inject, Injectable } from '@nestjs/common';
import { AlarmService } from 'src/module/alarm/alarm.service';
import { TestExternalPaymentSDK } from './payment.external.sdk';
import {
  PaymentInfo,
  Payment,
  RefundPaymentInfo,
  PaymentInfoForRefund,
} from './payment.model';
import { PaymentRepository } from './payment.repository';
import { AlarmData } from 'src/module/alarm/alarm.service';

@Injectable() // 비즈니스 로직으로 분리
export class PaymentService {
  
  constructor(
    @Inject('PaymentRepository')
    private readonly repository: PaymentRepository,
    @Inject('AlarmService')
    private readonly alarmService: AlarmService,
  ) {}

  public async makePayment(paymentInfo: PaymentInfo): Promise<Payment> {
    this.validatePaymentInfo(paymentInfo);
    // DB작업 - 결제 정보 저장
    const savePaymentInfo = this.repository.savePayment(paymentInfo);

    // 결제 SDK 기능
    this.paymentToSdk(paymentInfo);

    // 결제 완료 알람 붙여야함

    const userPhoneNumber = await this.repository.findUserPhoneNumber(
      paymentInfo.userId,
    );
    let message = '결제가 완료되었습니다';

    const alarmData: AlarmData = {
      recipient: userPhoneNumber,
      message: message,
    };

    this.alarmService.sendAlarm(alarmData);

    return savePaymentInfo;
  }

...

```

```
//payment.repository.ts

import { PaymentInfo, Payment } from "./payment.model";
import { CardCompany } from "./payment.model";
import { RefundPaymentInfo, PaymentInfoForRefund } from "./payment.model";


export interface PaymentRepository {
    savePayment(paymentInfo: PaymentInfo): Promise<Payment>
    refundPayment(paymentInfo: RefundPaymentInfo): Promise<PaymentInfoForRefund>
    findUserPhoneNumber(userId: number): Promise<string>
  }

...

```

```
//payment.db.ts

import { Injectable } from '@nestjs/common';
import { PaymentRepository } from "../domain/payment.repository";
import { CardCompany, RefundPaymentInfo, PaymentInfoForRefund } from "../domain/payment.model";
import { PaymentInfo, Payment } from "../domain/payment.model";
import { PaymentEntity } from "./payment.entity";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { InvalidPaymentInfoError } from "../payment.error";
import { UserEntity } from 'src/module/user/data/user.entity';

// 실제 DB
@Injectable()
export class PaymentRepositoryImpl implements PaymentRepository {

    constructor(
        // DB 주입
        @InjectRepository(PaymentEntity)
        private PaymentDB: Repository<PaymentEntity>,
        private UserDB: Repository<UserEntity>
    ){}

    async savePayment(paymentInfo: PaymentInfo): Promise<Payment> {
           
        // user가 db에 존재하는지??
        const user = await this.UserDB.findOne({
            where: { id: paymentInfo.userId },
        });
        if (user === null) throw new InvalidPaymentInfoError('유저');


        // model -> entitiy
        const entity = this.PaymentDB.create({
            User: user,
            cardNum: paymentInfo.cardNum,
            endDate: paymentInfo.endDate,
            cvc: paymentInfo.cvc,
            cardCompany: paymentInfo.cardCompany,
            price: paymentInfo.price
          });
        
        await this.PaymentDB.save(entity);

        // entity -> model 로는 안바뀌도 되나오..?mapper를 못쓴다던 이유가 있었는데..

        return {
            paymentId: entity.id,
            userId : entity.User.id,
            cardNum: entity.cardNum,
            endDate: entity.endDate,
            cvc: entity.cvc,
            cardCompany: paymentInfo.cardCompany,
            price : entity.price
        }
    }

    async refundPayment(refundInfo: RefundPaymentInfo): Promise<PaymentInfoForRefund> {

        // 요청에 들어온 paymentId가 db에 존재하는지?
        const payment = await this.PaymentDB.findOne({
            where: { id: refundInfo.paymentId}
        });
        if (payment === null) throw new InvalidPaymentInfoError('결제 PK');

        // user가 db에 존재하는지??
        const user = await this.UserDB.findOne({
            where: { id: refundInfo.userId },
        });
        if (user === null) throw new InvalidPaymentInfoError('유저');

        // 소프트 딜리트 - 환불 처리됨
        payment.isRefund = true; // 원하는 칼럼을 true로 변경
        await this.PaymentDB.save(payment); // 변경 내용을 저장

        // entitiy -> domain
        const refundPaymentDomain: PaymentInfoForRefund = {
            userId: payment.User.id,
            cardNum: payment.cardNum,
            endDate: payment.endDate,
            cvc: payment.cvc,
            cardCompany: payment.cardCompany,
            price: payment.price,
          };

        return refundPaymentDomain;

    }

    async findUserPhoneNumber(userId: number): Promise<string> {
        // user가 db에 존재하는지??
        const user = await this.UserDB.findOne({
            where: { id: userId },
        });

        if (user === null) throw new InvalidPaymentInfoError('유저');

        return user.phoneNumber;
    }
}
```

**Comment by codesejin** [comment]
코드 내 의존성 재 확인 후 문제 해결했습니다
